### ISSUE TITLE
MaxiGallery 0.6

### ISSUE THREAD

**Issue by pmfx** [yama/MaxiGallery#3]
Some time ago I found [on forums](https://forums.modx.com/thread/?thread=4973) MaxiGallery v0.6 and I wonder if this repo is using v0.6 code. Unfortunately there is no download link there any more but I have a copy of it though. 

Here it is: [maxigallery-0.6.zip](https://github.com/yama/MaxiGallery/files/669921/maxigallery-0.6.zip)

I've been using this 0.6 version since then and haven't got any problems. So my question is: should this repo be upgraded with this version and is it compatible?

**Comment by yama** [comment]
[new-maxigallery06.zip](https://github.com/yama/MaxiGallery/files/670125/new-maxigallery06.zip)
Merged it. Would you test if this works or not?

**Comment by pmfx** [comment]
Hey @yama thanks. I've tested it on MODX 1.0.15 and all looks good. Works as expected :) 
Is it compatible with MODX 1.2.0?

**Comment by yama** [comment]
Yes, compatible
https://github.com/extras-evolution/MaxiGallery/commits/master
Merged

**Comment by pmfx** [comment]
Great, thanks!
